# Generated by Django 5.0.6 on 2024-07-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_type_course_assessment_grade_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.TextField(max_length=500),
        ),
    ]
