# Generated by Django 5.0.6 on 2024-07-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_course_code_alter_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='title',
            field=models.TextField(default='Title', max_length=500),
            preserve_default=False,
        ),
    ]
