# Generated by Django 5.0.6 on 2024-07-15 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_assessment_description_assessment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='main.assessment'),
        ),
    ]
