# Generated by Django 5.0.6 on 2024-07-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_assessment_description_alter_grade_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
