# Generated by Django 5.0.6 on 2024-07-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_assessment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='answers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
