# Generated by Django 5.0.6 on 2024-07-30 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_feedbackmessage_sent_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='material',
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='main.course')),
            ],
        ),
    ]
